#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.player"
CFG="$HOME/.config/eww/music_player"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open music
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
    # remove old search data
	run_eww
    eww -c $HOME/.config/eww/music_player update valid=false
    eww -c $HOME/.config/eww/music_player update title=""
    eww -c $HOME/.config/eww/music_player update album=""
    eww -c $HOME/.config/eww/music_player update artist=""
else
	${EWW} --config "$CFG" close music
	rm "$FILE"
fi
