#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.player"
CFG="$HOME/.config/eww/music_player"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open music
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
    # remove old search data
    rm $CFG/scripts/data.txt
	run_eww
else
	${EWW} --config "$CFG" close music
	rm "$FILE"
fi
